spring:
  data:
    mongodb:
      host: 172.26.45.191
      port: 27017
      database: eghackathoncare

server:
  port: 8080
  contextPath: /egencia-care

logging:
 level:
  com.egencia.hackathon: INFO
  org.springframework: INFO

endpoints:
  info:
    enabled: true